In [1]:
import pandas as pd
import numpy as np

In [14]:
df = pd.read_csv("messages.csv")
df.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [15]:
df.drop(columns=['msg'], inplace=True)

## **Working with date**

In [16]:
df['date'] = pd.to_datetime(df['date'])

In [19]:
df['day'] = df['date'].dt.day
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year
df['month_name'] = df['date'].dt.month_name()

In [20]:
df.head()

                 date  day  month  year month_name
0 2013-12-15 00:50:00   15     12  2013   December
1 2014-04-29 23:40:00   29      4  2014      April
2 2012-12-30 00:21:00   30     12  2012   December
3 2014-11-28 00:31:00   28     11  2014   November
4 2013-10-26 23:11:00   26     10  2013    October

## **Working with Time**

In [21]:
df.head()

                 date  day  month  year month_name
0 2013-12-15 00:50:00   15     12  2013   December
1 2014-04-29 23:40:00   29      4  2014      April
2 2012-12-30 00:21:00   30     12  2012   December
3 2014-11-28 00:31:00   28     11  2014   November
4 2013-10-26 23:11:00   26     10  2013    October

In [24]:
df['hour'] = df['date'].dt.hour
df['minute'] = df['date'].dt.minute
df['second'] = df['date'].dt.second

In [25]:
df.head()

                 date  day  month  year month_name  hour  minute  second
0 2013-12-15 00:50:00   15     12  2013   December     0      50       0
1 2014-04-29 23:40:00   29      4  2014      April    23      40       0
2 2012-12-30 00:21:00   30     12  2012   December     0      21       0
3 2014-11-28 00:31:00   28     11  2014   November     0      31       0
4 2013-10-26 23:11:00   26     10  2013    October    23      11       0